header:
  productionDescription: > 
     <p>This API grouping enables access to pertinent information about accounts within a financial institution, transactions related to those accounts and relationships between accounts and accountholders. </p><ul><li> Account lists</li><li> Transaction data</li><li> Balance information</li></ul>
steps:  
  learnSteps:
    - title: Learn
      description: >
        Use the Fiserv Developer Portal to discover your next integration project. Developers can explore the APIs in our intelligent API Explorer.
      link:
  buildSteps:
    - title: Build
      description: >
        Leverage our sample code to get your application coded quickly. Developers can employ our Sandbox environment to create robust solutions.
      link:
  validateSteps:
    - title: Validate
      description: >
        Test your application end-to-end in our latest Sandbox environment. Use our state-of-the-art features to make your application more robust.
      link:
  deploySteps:
    - title: deploy
      description: >
        When your application is ready for deployment, submit it for our automated certification. Once certified, it can be deployed to the production.
      link:
featuredFeatures:
  - title: Accounts
    description: >
      Provides pertinent information about accounts within a financial institution and relationships between accounts and accountholders
  - title: Transactions
    description: >
      Provides transactions related to those accounts.
benefits:
  - title: Lists
    description: >
      Obtain a list of accounts, their balances and essential information.
  - title: Analysis and alerting
    description: Gather transaction data for analysis and alerting.
featuredAPIs:
  - name: Charges
    description: Used to submit a charge transaction.
    type: POST
    route: /payments/v1/charges
    codeSample: '[json
                  {
                     "amount":{
                        "total":"12.04",
                        "currency":"USD"
                     },
                     "source":{
                        "sourceType":"PaymentCard",
                        "card":{
                           "cardData":"4005550000000019",
                           "expirationMonth":"02",
                           "expirationYear":"2035",
                           "securityCode":"123",
                           "securityCodeIndicator":"PROVIDED"
                        }
                     },
                     "transactionDetails":{
                        "captureFlag":true
                     }
                  }]'
    language: Curl
    link: link to API Explorer
  - name: Tokenization
    description: Transaction data is protected by a randomly-generated identifier known as a "token".
    type: POST
    route: /payments-vas/v1/tokens
    codeSample: '[json
                  {
                     "amount":{
                        "total":"1.00",
                        "currency":"USD"
                     },
                     "source":{
                        "sourceType":"PaymentCard",
                        "card":{
                           "cardData":"4005550000000019",
                           "expirationMonth":"02",
                           "expirationYear":"2035",
                           "securityCode":"123"
                        }
                     },
                     "transactionDetails":{
                        "captureFlag":false,
                        "createToken":true,
                        "tokenProvider":"RSA"
                     }
                  }]'
    language: Curl
    link: link to API Explorer 
  - name: Verifications
    description: Confirm account validity and provide notification.
    type: POST
    route: /payments-vas/v1/accounts/verification
    codeSample: '[json
                  {
                     "source":{
                        "sourceType":"PaymentCard",
                        "card":{
                           "cardData":"4005550000000019",
                           "expirationMonth":"02",
                           "expirationYear":"2035"
                        }
                     }
                  }]'
    language: Curl
    link: link to API Explorer  
  - name: Capture
    description: Capture pending authorization for settlement post authorization.
    type: POST
    route: /payments/v1/charges/{transactionId}/capture
    codeSample: '[json
                  {
                    "amount": {
                      "total": "12.04",
                      "currency": "USD"
                    },
                    "transactionDetails": {
                      "captureFlag": true
                    }
                  }]'
    language: Curl
    link: link to API Explorer   
useCases:
  - title: Business to business
    subtitle: B2B
    description: > 
      Obtain robust configuration and account details.
  - title: Business to consumer
    subtitle: B2C
    description: > 
      For applications targeting consumers, our lightweight APIs provide essential account and transaction data in a smaller payload.
